export const sample_foods = [
    {
        id: '1',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favourite: true,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '2',
        name: 'Hamburger',
        cookTime: '25',
        price: 7,
        favourite: false,
        origins: ['spain'],
        stars: 3.5,
        imageUrl: 'food-2.jpg',
        tags: ['FastFood', 'Hamburger', 'Lunch'],

    },
    {
        id: '3',
        name: 'Macaroni and Cheese',
        cookTime: '2',
        price: 3,
        favourite: false,
        origins: ['france'],
        stars: 2,
        imageUrl: 'food-3.jpg',
        tags: ['FastFood', 'Macaroni and Cheese', 'Lunch'],
    },
    {
        id: '4',
        name: 'Meat Pie',
        cookTime: '3',
        price: 5,
        favourite: false,
        origins: ['australia'],
        stars: 3,
        imageUrl: 'food-4.jpg',
        tags: ['FastFood', 'MeatPie', 'Lunch'],
    },
    {
        id: '5',
        name: 'Sushi',
        cookTime: '15',
        price: 35,
        favourite: false,
        origins: ['japan'],
        stars: 4.5,
        imageUrl: 'food-5.jpg',
        tags: ['FastFood', 'Sushi', 'Lunch'],
    },
    {
        id: '6',
        name: 'Ube',
        cookTime: '45',
        price: 50,
        favourite: false,
        origins: ['phillipines'],
        stars: 4.5,
        imageUrl: 'food-6.jpg',
        tags: ['FastFood', 'Ube', 'Lunch'],
    }
    
]